name: Build

on:
  pull_request:
    paths-ignore:
      - charts/**
      - docs/**

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Run build
        run: make build-docker
